import os
from datetime import datetime
from fpdf import FPDF


# ---------------------------------------------------------------------------
# Helper: Make text safe for Helvetica (Latin-1)
# ---------------------------------------------------------------------------
def safe_text(text):
    """Replace unsupported Unicode characters with ASCII equivalents."""
    if text is None:
        return ""

    text = str(text)

    replacements = {
        "—": "-",
        "–": "-",
        "…": "...",
        "“": '"',
        "”": '"',
        "‘": "'",
        "’": "'",
        "•": "-",
        "→": "->",
        "✓": "OK",
        "✔": "OK",
        "📋": "",
        "📝": "",
        "⚖️": "",
        "✅": "",
        "🗒️": "",
        "👤": "",
        "📅": "",
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    return text.encode("latin-1", "replace").decode("latin-1")


# ---------------------------------------------------------------------------
# Custom PDF
# ---------------------------------------------------------------------------
class MeetingReportPDF(FPDF):
    """Meeting report PDF with custom header and footer."""

    def __init__(self, meeting_title: str):
        super().__init__()
        self.meeting_title = safe_text(meeting_title)
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, "AI Meeting Assistant", align="L")
        self.ln(5)

        self.set_font("Helvetica", "B", 13)
        self.set_text_color(30, 30, 30)
        self.cell(0, 8, safe_text(self.meeting_title), align="L")
        self.ln(2)

        self.set_draw_color(180, 180, 180)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)

        self.cell(
            0,
            10,
            safe_text(
                f"Page {self.page_no()} - Generated by AI Meeting Assistant"
            ),
            align="C",
        )


# ---------------------------------------------------------------------------
# Section title
# ---------------------------------------------------------------------------
def _section_title(pdf: FPDF, title: str):
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(37, 99, 235)

    pdf.cell(0, 8, safe_text(title), ln=True)

    pdf.set_draw_color(37, 99, 235)
    pdf.set_line_width(0.4)

    x = pdf.get_x()
    y = pdf.get_y()

    pdf.line(x, y, x + 190, y)
    pdf.ln(4)

    pdf.set_text_color(30, 30, 30)
    pdf.set_draw_color(0, 0, 0)


# ---------------------------------------------------------------------------
# Body text
# ---------------------------------------------------------------------------
def _body_text(pdf: FPDF, text: str):
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(40, 40, 40)
    pdf.multi_cell(0, 6, safe_text(text))
    pdf.ln(2)


# ---------------------------------------------------------------------------
# Metadata row
# ---------------------------------------------------------------------------
def _meta_row(pdf: FPDF, label: str, value: str):
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(80, 80, 80)

    pdf.cell(40, 6, safe_text(f"{label}:"))

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(30, 30, 30)

    pdf.cell(0, 6, safe_text(value), ln=True)


# ---------------------------------------------------------------------------
# Main PDF generator
# ---------------------------------------------------------------------------
def generate_pdf(
    meeting_id: int,
    results: dict,
    segments: list,
    meeting_title: str = "Meeting Report",
) -> str:

    exports_dir = os.path.join("data", "exports")
    os.makedirs(exports_dir, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    safe_title = "".join(
        c for c in meeting_title if c.isalnum() or c in (" ", "_", "-")
    ).strip()

    safe_title = safe_title.replace(" ", "_")

    filename = f"{safe_title}_{timestamp}.pdf"

    file_path = os.path.join(exports_dir, filename)

    pdf = MeetingReportPDF(meeting_title)
    pdf.add_page()

    generated_at = datetime.now().strftime("%B %d, %Y at %H:%M")

    _meta_row(pdf, "Generated", generated_at)
    _meta_row(pdf, "Model", results.get("model_used", "N/A"))
    _meta_row(pdf, "Meeting ID", str(meeting_id))

    if segments:
        total = int(segments[-1].get("end_time", 0))

        hours = total // 3600
        mins = (total % 3600) // 60
        secs = total % 60

        if hours:
            duration = f"{hours}h {mins}m {secs}s"
        else:
            duration = f"{mins}m {secs}s"

        _meta_row(pdf, "Duration", duration)

    pdf.ln(4)
    # -----------------------------------------------------------------------
    # SUMMARY
    # -----------------------------------------------------------------------
    _section_title(pdf, "Meeting Summary")

    summary = results.get("summary") or "No summary available."
    _body_text(pdf, summary)

    # -----------------------------------------------------------------------
    # ACTION ITEMS
    # -----------------------------------------------------------------------
    _section_title(pdf, "Action Items")

    action_items = results.get("action_items", [])

    if not action_items:
        _body_text(pdf, "No action items were identified.")
    else:
        for i, item in enumerate(action_items, 1):
            task = item.get("task", "N/A")
            assignee = item.get("assignee", "Unassigned")
            deadline = item.get("deadline", "Not specified")

            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(30, 30, 30)
            pdf.multi_cell(0, 6, safe_text(f"{i}. {task}"))

            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(90, 90, 90)

            pdf.cell(10)
            pdf.cell(
                0,
                5,
                safe_text(
                    f"Assignee: {assignee} | Deadline: {deadline}"
                ),
                ln=True,
            )

            pdf.ln(2)

    # -----------------------------------------------------------------------
    # KEY DECISIONS
    # -----------------------------------------------------------------------
    _section_title(pdf, "Key Decisions")

    decisions = results.get("key_decisions", [])

    if not decisions:
        _body_text(pdf, "No key decisions were identified.")
    else:
        for i, decision in enumerate(decisions, 1):
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(30, 30, 30)
            pdf.multi_cell(0, 6, safe_text(f"{i}. {decision}"))
            pdf.ln(1)

    # -----------------------------------------------------------------------
    # TRANSCRIPT
    # -----------------------------------------------------------------------
    pdf.add_page()

    _section_title(pdf, "Full Transcript")

    if segments:
        for seg in segments:
            start = int(seg.get("start_time", 0))

            hours = start // 3600
            mins = (start % 3600) // 60
            secs = start % 60

            if hours:
                timestamp = f"[{hours:02d}:{mins:02d}:{secs:02d}]"
            else:
                timestamp = f"[{mins:02d}:{secs:02d}]"

            text = seg.get("text", "").strip()

            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(37, 99, 235)
            pdf.cell(22, 6, timestamp)

            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(30, 30, 30)
            pdf.multi_cell(0, 6, safe_text(text))

            pdf.ln(1)

    else:
        transcript = results.get("transcript") or "No transcript available."
        _body_text(pdf, transcript)

    # -----------------------------------------------------------------------
    # SAVE PDF
    # -----------------------------------------------------------------------
    pdf.output(file_path)

    print(f"PDF saved successfully: {file_path}")

    return file_path